### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by fritx** [fritx/cross-unzip#1]
- [x] overwrite if exists (prompt could block, win32/unix) https://github.com/fritx/cross-unzip/commit/9c231ebe83cdf35a944cf034c7d324c5122e4ec9
- [x] ignore stdio (could block, unix) https://github.com/fritx/cross-unzip/commit/c876d0e80b7a9eaab3821277b83967fc773491d2
- [ ] exclude __MACOSX (redundant, mac)
- [ ] progress feedback
- [ ] promise migration (~~breaking new version~~ compatible with callback)

**Comment by kargpfen** [comment]
A state of progress would be great! Is it possible to implement it shortly?

**Comment by fritx** [comment]
@kargpfen hahah.. i am not sure! will look into it
